version: "3.0"  # optional since v1.27.0
services:
  fund-watch-bot:
    build: .
    # volumes:
    #   - .:/code
    #   - logvolume01:/var/log
    restart_policy:
      condition: on-failure
      delay: 2s
      max_attempts: 1000000
      window: 5s
volumes:
  fund-watch-bot:
    external:
      name: fund-watch-bot